import { IDakimakura } from "../../types/index";

const dakimakuras: IDakimakura[] = [
  {
    imgSrc: "./images/genshin-Jinn.jpg",
    price: "1490",
    name: "Jinn",
    title: "Genshin-Impact",
    gender: "Girl",
    colors: ["White", "Blue"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/2arvpo-5ko_1643224501.jpg",
    price: "1799",
    name: "Levi",
    title: "Attack on Titan",
    gender: "Boy",
    colors: ["White"],
    material: "Linen",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/30adeec8a79cb3ae53a945cddb58a4d2.jpg",
    price: "2150",
    name: "Ayanami Rei",
    title: "Evangelion",
    gender: "Girl",
    colors: ["White", "Blue"],
    material: "Cotton",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/135_dakimakura_genshin_impact_kaedehara_kadzuha.png",
    price: "2350",
    name: "Kadzuhara",
    title: "Genshin Impact",
    gender: "Boy",
    colors: ["Red", "White"],
    material: "Plush",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Toho Project Izayoi Sakuya.jpg",
    price: "1510",
    name: "Izayoi Sakuya",
    title: "Toho Project",
    gender: "Girl",
    colors: ["White", "Blue"],
    material: "Linen",
    isPopular: "No",
  },
  {
    imgSrc: "./images/full_21542-Genshin-Impact-Hutao.jpg",
    price: "2199",
    name: "Hutao",
    title: "Genshin Impact",
    gender: "Girl",
    colors: ["Red", "White"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Honoka Kosaka- Love Live.png",
    price: "1399",
    name: "Honoka Kosaka",
    title: "Love Live",
    gender: "Girl",
    colors: ["Pink"],
    material: "Synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/kazuha-genshin.jpg",
    price: "2799",
    name: "Kaedehara Kazuha",
    title: "Genshin Impact",
    gender: "Boy",
    colors: ["Red"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/kirito- sword art online.png",
    price: "2099",
    name: "Kirito",
    title: "Sword Art Online",
    gender: "Boy",
    colors: ["Black", "White"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Mike tokyo revenge.png",
    price: "1249",
    name: "Mike",
    title: "Tokyo Revenge",
    gender: "Boy",
    colors: ["Green"],
    material: "Synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/Rimuru- that time i got reincarnated as a slime.png",
    price: "1789",
    name: "Rimuru",
    title: "Reincarnated as a Slime",
    gender: "Boy",
    colors: ["Blue"],
    material: "Synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/satoru gojo- Jujutsu kaisen.png",
    price: "10001",
    name: "Satoru Gojo",
    title: "Jujutsu Kaisen",
    gender: "Boy",
    colors: ["Black", "White"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/violet- evergarden.png",
    price: "2002",
    name: "Violet",
    title: "Violet Evergarden",
    gender: "Girl",
    colors: ["White"],
    material: "Synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/yuri  - doki_doki_literature_club_.png",
    price: "1349",
    name: "Yuri",
    title: "Doki Doki Club",
    gender: "Girl",
    colors: ["Pink"],
    material: "Synthetic",
    isPopular: "No",
  },
];

export default dakimakuras;
