import { IDakimakura } from "../../types/index";

export const colors: string[] = [
  "white",
  "black",
  "blue",
  "green",
  "pink",
  "red",
];
export const materials: string[] = ["synthetic", "cotton", "plush", "linen"];
const dakimakuras: IDakimakura[] = [
  {
    imgSrc: "./images/genshin-Jinn.jpg",
    price: 1490,
    name: "Jinn",
    title: "Genshin-Impact",
    gender: "girl",
    colors: ["white", "blue"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/2arvpo-5ko_1643224501.jpg",
    price: 1799,
    name: "Levi",
    title: "Attack on Titan",
    gender: "boy",
    colors: ["white"],
    material: "linen",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/30adeec8a79cb3ae53a945cddb58a4d2.jpg",
    price: 2150,
    name: "Ayanami Rei",
    title: "Evangelion",
    gender: "girl",
    colors: ["white", "blue"],
    material: "cotton",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/135_dakimakura_genshin_impact_kaedehara_kadzuha.png",
    price: 2350,
    name: "Kadzuhara",
    title: "Genshin Impact",
    gender: "boy",
    colors: ["red", "white"],
    material: "plush",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Toho Project Izayoi Sakuya.jpg",
    price: 1510,
    name: "Izayoi Sakuya",
    title: "Toho Project",
    gender: "girl",
    colors: ["white", "blue"],
    material: "linen",
    isPopular: "No",
  },
  {
    imgSrc: "./images/full_21542-Genshin-Impact-Hutao.jpg",
    price: 2199,
    name: "Hutao",
    title: "Genshin Impact",
    gender: "girl",
    colors: ["red", "white"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Honoka Kosaka- Love Live.png",
    price: 1399,
    name: "Honoka Kosaka",
    title: "Love Live",
    gender: "girl",
    colors: ["pink"],
    material: "synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/kazuha-genshin.jpg",
    price: 2799,
    name: "Kaedehara Kazuha",
    title: "Genshin Impact",
    gender: "boy",
    colors: ["red"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/kirito- sword art online.png",
    price: 2099,
    name: "Kirito",
    title: "Sword Art Online",
    gender: "boy",
    colors: ["black", "white"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/Mike tokyo revenge.png",
    price: 1249,
    name: "Mike",
    title: "Tokyo Revenge",
    gender: "boy",
    colors: ["green"],
    material: "synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/Rimuru- that time i got reincarnated as a slime.png",
    price: 1789,
    name: "Rimuru",
    title: "Reincarnated as a Slime",
    gender: "boy",
    colors: ["blue"],
    material: "synthetic",
    isPopular: "No",
  },
  {
    imgSrc: "./images/satoru gojo- Jujutsu kaisen.png",
    price: 10001,
    name: "Satoru Gojo",
    title: "Jujutsu Kaisen",
    gender: "boy",
    colors: ["black", "white"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/violet- evergarden.png",
    price: 2002,
    name: "Violet",
    title: "Violet Evergarden",
    gender: "girl",
    colors: ["white"],
    material: "synthetic",
    isPopular: "Yes",
  },
  {
    imgSrc: "./images/yuri  - doki_doki_literature_club_.png",
    price: 1349,
    name: "Yuri",
    title: "Doki Doki Club",
    gender: "girl",
    colors: ["pink"],
    material: "synthetic",
    isPopular: "No",
  },
];

export default dakimakuras;
